version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: actinidia
    container_name: actinidia-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - actinidia
    environment:
      - PHP_IDE_CONFIG=serverName=${IDE_DEBUG_SERVER}
      - IDE_DEBUG_HOST=${IDE_DEBUG_HOST}

  mysql:
    image: mysql:8.0
    container_name: actinidia-mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - actinidia
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: actinidia-nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - actinidia

networks:
  actinidia:
    driver: bridge

volumes:
  mysql-data:
